### ISSUE TITLE
Why is data property assumed on response result in fetchr.client.js?

### ISSUE THREAD

**Issue by shoaibkalsekar** [yahoo/fetchr#127]
I am using fluxible and fluxible-plugin-fetchr for my app. I hit a roadblock when I saw the API server returning a response but `undefined` is passed all around. After a bit of debugging I found `results.data` https://github.com/yahoo/fetchr/blob/master/libs/fetcher.client.js#l144. I tried changing `results.data` to `results` and it worked fine. I couldn't find any explanation elsewhere so can someone please explain why data property is considered mandatory in response result?

**Comment by Vijar** [comment]
@shoaibkalsekar are you using `fetchr` as your api server?

**Comment by shoaibkalsekar** [comment]
@Vijar No. The api server is different.

**Comment by Vijar** [comment]
@shoaibkalsekar thats the problem.

When we released the latest fetchr we made changes to the data format that fetchr uses to communicate between server and client. But since you're using your own api server, there is no way we can guarantee things will not break in our releases.

We do NOT recommend that you use the fetchr client with a different api server than fetchr's server counterpart. This is because fetchr is only useful when used both on the server and client. Otherwise you get no advantages compared to a simple request library like [`superagent`](https://github.com/visionmedia/superagent).

Consider `superagent` for your needs.

**Comment by localnerve** [comment]
This hit me as well - In a use case you might (or might not) be interested in: Service Workers.

#### Background
I'm using fluxible-plugin-fetchr 0.3.8 by itself (on both server and client).

#### Use Case
I'm caching api responses in a service worker. Usually this works great. 
However, the `result.data` special difference is exposed when you have to synthesize a response from other cached/stored data (not from the original response). In this case, you have to 'just know' about this response format quirk that now exists in fetchr.

So, until the result data/meta split, this knowledge was not required to leak outside. A response was a response.

#### Reason for synthesized api response in Fluxible
The reason for synthesizing an api response in a Fluxible app (and there is only one I've found), is that the initial render (server-side) never has to make a client side api request - Because that is done on the server in the initial render.
The service worker is caching api requests, but not ones that are never made.
So in an offline situation, when an api request is made (that would normally have been server-side rendered), it is possible to fallback to the content that was server-side rendered back when the app was online.
This is the case where you can synthesize an api response with real data, and the user continues on none-the-wiser.

This worked for me opaquely until the data/meta result division. Now that Fetchr detail has to leak into the service worker response synthesis.

@mridgway @Vijar

**Comment by Vijar** [comment]
@localnerve 

This is a hard problem to solve but when we released the new version, fetchr started sending a new query param `returnMeta` with each GET request. This is what fetchr server uses to switch between the response formats. My goal was that this new query param would bust typical http caching and force a new fetch from the origin, however it seems like your code is only using the resource as a cache key and not the entire url?

**Comment by localnerve** [comment]
I appreciate the problem (and this great repo), I just wanted to share a use case that is impacted by this type of change, and highlight that non-standard response formatting like that can (and does in my case of 'offline Fluxible') cause implementation leakage.

If your goal was cache busting, why does it carry over to the response format? I don't understand why cache busting would impose non-standard response format. It seems (to me) that it is trying to do two responses in one (data/meta) at the top level of the response body, and that imposed the formatting.
I'll have to read your code more to understand better - I'm not sure there is a reasonable alternative if meta must also go in the response body.
Just for the record, the imposition of a non-standard response format I'm referring to is [here](https://github.com/yahoo/fetchr/blob/2060f317797836e40a9c84ccac7294eb8449d5dc/libs/fetcher.client.js#L144).

> ... however it seems like your code is only using the resource as a cache key and not the entire url?

The resource key usage you saw is used to lookup a correct response from a Flux store (ContentStore) copy in IndexedDB - But *only* in the event of a cache miss. On a cache miss, the flux store in IndexedDB would have the best available api response (looks in ContentStore for a resource match). Those copies are kept up-to-date as much as possible, also using a networkFirst strategy.

#### How I use Fetchr Urls in Service Worker
So that [response 'synthesis' code](https://github.com/localnerve/flux-react-example-sw/blob/6c53b6ba6ef311739f352162d0402197298671fa/assets/scripts/sw/init/stores.js#L101) is a fallback for a cache miss in a [networkFirst caching strategy](https://jakearchibald.com/2014/offline-cookbook/#network-falling-back-to-cache).
The networkFirst strategy uses the Fetchr urls and responses 'as-is' - **except** the request url used for cache lookups has the CSRF token ripped off, for good reason. To remove the CSRF token for effective cache lookups, I remove the entire querystring, so I guess I'm also removing `returnMeta`.
I'll only need to parse querystring if it starts to include items I need to distinguish a unique Fetchr api request (for cache lookup). Note: The Service Worker spec includes an option to remove querystrings (presume this purpose), but it's not yet implemented in browsers.

For reference, the networkFirst setup for Fetchr requests is [here](https://github.com/localnerve/flux-react-example-sw/blob/6c53b6ba6ef311739f352162d0402197298671fa/assets/scripts/sw/apis.js#L74): The `networkRequest` url is Fetchr 'as-is', the `cacheRequest` is without querystring (removes CSRF token, and `returnMeta`), and `resourceContentResponse` is the cache fallback (the code that was affected by the non-standard response format).

**Comment by mattpage** [comment]
This was a major pain to track down and the docs don't give any indication that the response needs to be { data: { ... } }. Would it be possible to document this in the README?
