### ISSUE TITLE
Return the request object from fetchr call

### ISSUE THREAD

**Issue by praveenbnsm** [yahoo/fetchr#142]
Return the request object that has been created while making a fetchr call. Similar to the following

```javascript
var req = 	fetchr
			    .read('data_service')
			    .params({id: ###})
			    .end(function (err, data, meta) {
			    // handle err and/or data returned from data fetcher in this callback
			    });
```

Incase if we have to abort the request, it can be easily done just by doing
```javascript
req.abort();
```

Currently, there is no way of aborting the request that has been made using fetchr. A better use case will be when using fetchr for a component like auto-suggestion box, where-in we can abort the fetchr service calls that are already made (as the user types) and only fetch the data for the final query which user has typed-in.

**Comment by Vijar** [comment]
@praveenbnsm I understand your problem but right now the `.end()` method actually returns a promise so that you can continue to chain promises. So the feature you ask for isn't trivial to implement.

For an autocomplete feature, it is probably too slow to create this many xhr calls only to abort them later, I would suggest [debouncing](https://lodash.com/docs#debounce) the event and calling fetchr in the debounced function. Have you tried debouncing?

**Comment by praveenbnsm** [comment]
@Vijar, I haven't tried debouncing. This can only help as a workaround to reduce the number of calls being made.
