### ISSUE TITLE
Working with mobile apps (as restful service)

### ISSUE THREAD

**Issue by umidbekkarimov** [yahoo/fetchr#82]
Greetings, thanks for awesome lib (remembered gwt simplicity)

I have question about using fetcher services for mobile apps without manually fulfilling `req.body.request.g0` fields, 

currently only `GET` method return proper response,

so can you provide any example of usage fetchr as a restful api

**Comment by Vijar** [comment]
@umidbekkarimov Fetchr isn't really meant to be a restful backend for your data (in fact fetchr isn't strictly REST-ful). It is only meant to help you write the same javascript on the server and client to access your data.

As for the `req.body.request.g0` that format is what `fetcher.client.js` follows on the client so that is what the `fetcher.js` on the server expects. This format is internal to Fetcher and should not be relied on for direct access as it could change in the future when we implement batching or other features.

We recommend you build your restful service independently from your Fetchr/Fluxible based app.

**Comment by umidbekkarimov** [comment]
@Vijar thanks for quick response, 

I wanted to write same code for client/web-server/api-service, well i will try to find some other options, thanks.

**Comment by koulmomo** [comment]
@umidbekkarimov take a look at [fluxible-plugin-service-proxy](https://github.com/benbria/node-fluxible-plugin-service-proxy)

**Comment by umidbekkarimov** [comment]
@Vijar oh, interesting lib, thanks,

But i tied up my app with fetchr services so i decided to use them with express router,
here the example if someone is interested https://gist.github.com/umidbekkarimov/61f2a1ecc3195a5cd3c6
