### ISSUE TITLE
return data is lost on error

### ISSUE THREAD

**Issue by lukemadera** [yahoo/fetchr#97]
Following the standard node convention, a callback with a non-null first argument signifies an error and often there is valuable error information passed back. However, in the current implementation, on error, the data is lost (overwritten with `message: err.message || 'request failed'`).

https://github.com/yahoo/fetchr/blob/master/libs/fetcher.js#L109

This is a significant issue since we are currently trying to validate form input fields and need a key value error object of errors per input. More generally, whatever error information or data is supplied should be passed through.
Any particular reason neither error nor data are passed through?

Solution should be pretty simple, such as:

```js
if (err) {
  res.status(err.statusCode || 400).json(err);
  return;
}
```

**Comment by davidhouweling** [comment]
After writing up my fix for #90 I understand now why they did what they did initially. I think a more appropriate solution would be to start with a generic error object with a message attribute, and then extend it with the data your wish to have transmitted across the wire. This way the original added value isn't lost.

**Comment by lukemadera** [comment]
You mean like this @davidhouweling ?

```js
if (err) {
  err =_.extend({message: err.message || 'request failed'}, err);
  res.status(err.statusCode || 400).json(err);
  return;
}
```

**Comment by davidhouweling** [comment]
Yes something along those lines, though I wouldn't pull in the whole underscore library to do it, even though it is just execution on server side (from memory).

I'd probably go with Object.assign if you can get away with it, or an npm module that implements it. This way when the codebase does move entirely to ES6, the code itself is already there and not requiring refactoring.

**Comment by lukemadera** [comment]
Yeah that was just a proof of concept but I agree @davidhouweling  - how's this:

if (err) {
  if(!err.message) {
    err.message ='request failed';
  }
  res.status(err.statusCode || 400).json(err);
  return;
}

**Comment by Vijar** [comment]
@lukemadera 

I think we could support this.

I was just experimenting with the code sample you have and it looks like passing in an error object into `res.json` has weird behavior. I've noticed that it ignores the `message` property.

**Comment by lukemadera** [comment]
Great @Vijar ! What seems to be the problem with message? It just gets omitted?

**Comment by Vijar** [comment]
Yeah it just doesn't get serialized.

**Comment by jeffkole** [comment]
Yes, the fields of an `Error` are not enumerable, so they are not serialized as JSON:

`Object.keys(new Error('request failed'))` results in `[]`

What about if we did this:

```javascript
if (err) {
  var data = {
    message: err.message || 'request failed',
    name: err.name,
    type: err.type,
    statusCode: err.statusCode || 400
  }
  res.status(err.statusCode || 400).json(data);
  return;
}
```

**Comment by Vijar** [comment]
@jeffkole I think we can support this. Want to do a PR?

**Comment by jeffkole** [comment]
I started working on this last night and after looking more closely at the client code realized it would be more difficult than necessary, because of the support for batching up requests.  If there is an error during a batch, the same error object is sent to each pending request (as seen in [fetchr.client.js](https://github.com/yahoo/fetchr/blob/898247ff935d84e59e8cd1121e2f083a2a61795c/libs/fetcher.client.js#L484)).  That would not be helpful in this case.  In fact, that points out to me that the error is really meant to signify a server or network error and not a user or data error.

So, I am going to explore changing how we use Fetchr to send back more data in a response even if it is technically a "failed" request.  In other words, a validation error will not result in a HTTP status code other than 200, but the response body will have to be checked for an object that holds error information.

Does that sound like a reasonable use of the library as is?

**Comment by Vijar** [comment]
So, `fetchr`'s batching doesn't really work right now...you can safely ignore that part of `fetchr.client.js`.

**Comment by jeffkole** [comment]
I'd feel safer ignoring it if it were gone entirely.  If there is intention to support batches, then I'd rather see progress there then on sending back data in error objects.  For what it is worth, batching would be incredibly useful so that we can have fetchers for individual entities and still feel good about only making a single request to the server to load a page.

**Comment by Bazze** [comment]
@jeffkole: Have you done any progress on this? I'm in the same situation as you and really need to pass with validation errors to the client. However, I'm not sure if I agree with you that it's a good idea to respond to erroneous requests (i.e. requests containing data with invalid data) with a 200 status code. Did you continue with that approach?

**Comment by jeffkole** [comment]
I did continue with that approach.  While not technically "correct," it works well with the current incarnation of Fetchr, and I'm pleased with it enough for the time being.

**Comment by KATT** [comment]
I'd also really want a way of returning more than just an error message to the client. Found this thread while digging into how I would return validation errors for a form, and yeah, it's not possible currently. 

Has anyone done/started with a fork? Otherwise I could just go ahead. 

The only difficult part of it is to make sure we serialise this in a safe way and don't leak the whole error object.

#### Idea draft

##### 1. Support a method `.toSafeJSON` on the passed error

```js
if (err) {
    var errJSON = {
        message: err.message || 'request failed'
    };
    if (typeof err.toSafeJSON === 'function') {
        errJSON = err.toSafeJSON();
    }
    res.status(err.statusCode || 400).json(errJSON);
    return;
}
```


##### 2. In your implementation, extend the built-in `Error` with a new method

```jsx

class ValidationError extends Error {
    constructor(validationErrors) {
        super();

        this.statusCode = 400;
        this.message = 'Validation error';

        this.validationErrors = validationErrors;
    }

    toSafeJSON() {
        return {
            message         : this.message,
            validationErrors: this.validationErrors,
        };
    }
}
```

**Comment by KATT** [comment]
Thoughts on the above? I can fork, do it and add tests if any of the authors gives me a :+1:

**Comment by redonkulus** [comment]
#113 was merged and released. Closing this issue.
